=== luispc1998/Sew/sew/practicaxml/ejercicio1/Tarea-1/rutas.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT rutas (ruta,ruta,ruta,ruta,ruta,ruta*)>
<!ELEMENT ruta (tipo, transporte, fechaInicio?,horaInicio?,
				duracion, agencia, descripcion, personasAdecuadas,
				lugarInicio, direccionInicio, coordenadas, referencias,
				recomendacion, hitos)>
				
<!ATTLIST ruta nombre CDATA #REQUIRED>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT fechaInicio (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personasAdecuadas (#PCDATA)>
<!ELEMENT lugarInicio (#PCDATA)>
<!ELEMENT direccionInicio (#PCDATA)>
<!ELEMENT coordenadas (longitud,latitud,altura)>
	<!ELEMENT longitud (#PCDATA)>
	<!ELEMENT latitud (#PCDATA)>
	<!ELEMENT altura (#PCDATA)>
	
<!ELEMENT referencias (referencia,referencia,referencia,referencia*)>
	<!ELEMENT referencia (#PCDATA)>
	
<!ELEMENT recomendacion (#PCDATA)>

<!ELEMENT hitos (hito,hito,hito,hito*)>
	<!ELEMENT hito (descripcionHito,coordenadas,fotos,videos?)>
		<!ATTLIST hito nombre CDATA #REQUIRED>
		<!ATTLIST hito distanciaAnteriorHito CDATA #REQUIRED>
		<!ELEMENT descripcionHito (#PCDATA)>
		<!ELEMENT fotos (foto, foto?,foto?,foto?,foto?)>
		<!ELEMENT foto (#PCDATA)>
		<!ELEMENT videos (video?, video?, video?)>
		<!ELEMENT video (#PCDATA)>

=== luispc1998/Sew/sew/practicaxml/ejercicio1/Tarea-1/tarea1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
	<ruta nombre="Ruta por Oviedo">

		<tipo>Arquitectura y Monuemntos</tipo>   
		<transporte>A pie</transporte>
		<duracion>4 horas</duracion>
		<agencia>Sin agencia</agencia>
		<descripcion>Gran ruta para respirar aire fresco</descripcion>
		<personasAdecuadas>Buena forma física</personasAdecuadas>
		<lugarInicio>Oviedo</lugarInicio>
		<direccionInicio>calle Foncalada</direccionInicio>
		<coordenadas>
			<longitud>-5.8473945</longitud>
			<latitud>43.3643082</latitud>
			<altura>230</altura>
		</coordenadas>
		<referencias>
			<referencia>Referencia 1: https://www.turismoasturias.es/descubre/cultura/prerromanico/la-foncalada</referencia>
			<referencia>Referencia 2: https://es.wikipedia.org/wiki/Foncalada</referencia>
			<referencia>Referencia 3: https://www.tripadvisor.es/Attraction_Review-g187452-d6562436-Reviews-Fuente_de_Foncalada-Oviedo_Asturias.html</referencia>
		</referencias>
		<recomendacion>8</recomendacion>
		<hitos>
			<hito nombre = "La fuente" distanciaAnteriorHito="200">
				<descripcionHito>Hermosa fuente</descripcionHito>
				<coordenadas>
					<longitud>-5.8654631</longitud>
					<latitud>43.3630078</latitud>
					<altura>249</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto1.jpg</foto>
					<foto>./img/Foto2.jpg</foto>
					<foto>./img/Foto3.jpg</foto>
				</fotos>
			</hito>


			<hito nombre = "San Miguel de Lillo" distanciaAnteriorHito="300">
				<descripcionHito>Iglesia prerrománica</descripcionHito>
				<coordenadas>
					<longitud>5.86837466</longitud>
					<latitud>43.38030365</latitud>
					<altura>395</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto4.jpg</foto>
					<foto>./img/Foto5.jpg</foto>
					<foto>./img/Foto6.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


			<hito nombre = "Catedral" distanciaAnteriorHito="200">
				<descripcionHito>Única catedral española de una sola torre</descripcionHito>
				<coordenadas>
					<longitud>-5.84329398</longitud>
					<latitud>43.36252235</latitud>
					<altura>241</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto7.jpg</foto>
					<foto>./img/Foto8.jpg</foto>
					<foto>./img/Foto9.jpg</foto>
				</fotos>
			</hito>

		</hitos>

	</ruta>

	<ruta nombre="Ruta por Gijón">

		<tipo>Arquitectura y Monuemntos</tipo>   
		<transporte>A pie</transporte>
		<fechaInicio>2019-10-29</fechaInicio>
		<horaInicio>17:00</horaInicio>
		<duracion>4 horas</duracion>
		<agencia>PanchitosSL</agencia>
		<descripcion>Buena ruta para conocer la costa de gijón</descripcion>
		<personasAdecuadas>Apta para todos los públicos</personasAdecuadas>
		<lugarInicio>Gijon</lugarInicio>
		<direccionInicio>camín de la iglesia</direccionInicio>
		<coordenadas>
			<longitud>-5.7002914</longitud>
			<latitud>43.54703692</latitud>
			<altura>10</altura>
		</coordenadas>
		<referencias>
			<referencia>Referencia 1: https://www.gijon.es/</referencia>
			<referencia>Referencia 2: https://es.wikipedia.org/wiki/Gij%C3%B3n</referencia>
			<referencia>Referencia 3: http://www.gijon.info/</referencia>
		</referencias>
		<recomendacion>8</recomendacion>
		<hitos>

			<hito nombre = "el musel" distanciaAnteriorHito="200">
				<descripcionHito>Gran puerto internacional de gijón</descripcionHito>
				<coordenadas>
					<longitud>-5.7023349</longitud>
					<latitud>43.5656368</latitud>
					<altura>7</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto3.jpg</foto>
				</fotos>
			</hito>


			<hito nombre = "la campa torres" distanciaAnteriorHito="300">
				<descripcionHito>Campamento de la antiguedad</descripcionHito>
				<coordenadas>
					<longitud>-5.7036463</longitud>
					<latitud>43.5699203</latitud>
					<altura>100</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto4.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


			<hito nombre = "Monumento al horizonte" distanciaAnteriorHito="400">
				<descripcionHito>Bonito monumento rodeado de playas</descripcionHito>
				<coordenadas>
					<longitud>-5.6630529</longitud>
					<latitud>43.5470241</latitud>
					<altura>28</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto7.jpg</foto>
					<foto>./img/Foto8.jpg</foto>
					<foto>./img/Foto9.jpg</foto>
					<foto>./img/Foto10.jpg</foto>
				</fotos>
			</hito>

		</hitos>
	</ruta>

	<ruta nombre="Ruta por Pola de Siero">

		<tipo>Arquitectura y Monuemntos</tipo>   
		<transporte>En bus</transporte>
		<horaInicio>19:00</horaInicio>
		<duracion>3 horas</duracion>
		<agencia>Mariano</agencia>
		<descripcion>Buena ruta para conocer la costa de gijón</descripcion>
		<personasAdecuadas>Tercera edad</personasAdecuadas>
		<lugarInicio>Gijon</lugarInicio>
		<direccionInicio>calle ramon y cajal</direccionInicio>
		<coordenadas>
			<longitud>-5.66074848</longitud>
			<latitud>43.3922863</latitud>
			<altura>213</altura>
		</coordenadas>
		<referencias>
			<referencia>Referencia 1: https://es.wikipedia.org/wiki/Pola_de_Siero</referencia>
			<referencia>Referencia 2: https://www.desdeasturias.com/pola-de-siero-informacion/</referencia>
			<referencia>Referencia 3: http://www.ayto-siero.es/</referencia>
		</referencias>
		<recomendacion>8</recomendacion>
		<hitos>

			<hito nombre = "Palacio de Celles" distanciaAnteriorHito="900">
				<descripcionHito>Antiguo palacio semiderruido</descripcionHito>
				<coordenadas>
					<longitud>-5.6653513</longitud>
					<latitud>43.3997812</latitud>
					<altura>230</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto3.jpg</foto>
				</fotos>
			</hito>


			<hito nombre = "Iglesia de San Pedro" distanciaAnteriorHito="300">
				<descripcionHito>Iglesia prerrománica</descripcionHito>
				<coordenadas>
					<longitud>-5.66450357</longitud>
					<latitud>43.39301395</latitud>
					<altura>225</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto4.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


			<hito nombre = "Palacio del Marqués" distanciaAnteriorHito="400">
				<descripcionHito>Antiguo palacio del marqués</descripcionHito>
				<coordenadas>
					<longitud>-5.65914631</longitud>
					<latitud>43.39198224</latitud>
					<altura>219</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto7.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


		</hitos>
	</ruta>


	<ruta nombre="Ruta por Lieres">

		<tipo>Arquitectura y Monumentos</tipo>   
		<transporte>En bus</transporte>
		<horaInicio>19:00</horaInicio>
		<duracion>3 horas</duracion>
		<agencia>Mariano</agencia>
		<descripcion>Buena ruta para conocer los alrededores de lieres</descripcion>
		<personasAdecuadas>Tercera edad</personasAdecuadas>
		<lugarInicio>Lieres</lugarInicio>
		<direccionInicio>calle de la estación</direccionInicio>
		<coordenadas>
			<longitud>-5.58248162</longitud>
			<latitud>43.3807025</latitud>
			<altura>239</altura>
		</coordenadas>
		<referencias>
			<referencia>Referencia 1: https://es.wikipedia.org/wiki/Lieres</referencia>
			<referencia>Referencia 2: https://www.viamichelin.es/web/Mapas-Planos/Mapa_Plano-Lieres-33580-Asturias-Espana</referencia>
			<referencia>Referencia 3: https://www.pueblosdeasturias.es/siero/lieres</referencia>
		</referencias>
		<recomendacion>8</recomendacion>
		<hitos>

			<hito nombre = "Cementerio" distanciaAnteriorHito="900">
				<descripcionHito>Cementerio decordado con multiples esculturas</descripcionHito>
				<coordenadas>
					<longitud>-5.57034731</longitud>
					<latitud>43.38037629</latitud>
					<altura>255</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto3.jpg</foto>
				</fotos>
			</hito>


			<hito nombre = "Iglesia Lieres" distanciaAnteriorHito="300">
				<descripcionHito>Iglesia del siglo XVIII</descripcionHito>
				<coordenadas>
					<longitud>-5.57139874</longitud>
					<latitud>43.38061023</latitud>
					<altura>259</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto4.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


			<hito nombre = "Solvay" distanciaAnteriorHito="400">
				<descripcionHito>Antiguo mina de lieres</descripcionHito>
				<coordenadas>
					<longitud>-5.57766438</longitud>
					<latitud>43.37041895</latitud>
					<altura>272</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto7.jpg</foto>
				</fotos>

				<videos>
					<video>./vid/Video1.mp4</video>
				</videos>
			</hito>


		</hitos>
	</ruta>

	<ruta nombre="Ruta por Oviedo">

		<tipo>Culinaria</tipo>   
		<transporte>A Pie</transporte>
		<horaInicio>18:00</horaInicio>
		<duracion>6 horas</duracion>
		<agencia>Sin Agencia</agencia>
		<descripcion>Buena ruta para comer deliciosa comida</descripcion>
		<personasAdecuadas>Todos los públicos</personasAdecuadas>
		<lugarInicio>Oviedo</lugarInicio>
		<direccionInicio>calle uría</direccionInicio>
		<coordenadas>
			<longitud>-5.8545854</longitud>
			<latitud>43.366161</latitud>
			<altura>220</altura>
		</coordenadas>
		<referencias>
			<referencia>Referencia 1: https://elfartuquin.es</referencia>
			<referencia>Referencia 2: https://www.tripadvisor.es/Restaurants-g187452-Oviedo_Asturias.html</referencia>
			<referencia>Referencia 3: hhttps://www.mcdonalds.es/</referencia>
		</referencias>
		<recomendacion>8</recomendacion>
		<hitos>

			<hito nombre = "Fartuquín" distanciaAnteriorHito="300">
				<descripcionHito>Gran restaurante apto para celíacos</descripcionHito>
				<coordenadas>
					<longitud>-5.84327194</longitud>
					<latitud>43.35937091</latitud>
					<altura>230</altura>
				</coordenadas>
				<fotos>
					<foto>./img/Foto3.jpg</foto>
				</fotos>
			</hito>


			<hito nombre = "El Carro" distanciaAnteriorHito="300">
				<descripcionHito>Restaurante de buena fama</descripcionHito>
				<coordenadas>
					<longitud>-5.84355172</longitud>
